# Generated by Django 4.2.8 on 2024-04-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Номер телефона'),
        ),
    ]
